import { Activity, CarFront, Clock3, Gauge, ShieldCheck, Siren, UsersRound, Wifi, WifiOff, AlertTriangle } from 'lucide-react';
import { useState } from 'react';
import TrafficIntersection from '../components/TrafficIntersection';
import { EventLog, MetricCard, PageIntro, SafetyPanel, SectionHeading, StatusBadge, TrafficCard, TrendChart } from '../components/Shared';
import { densityData, eventLog, queueData, waitingData } from '../data/sampleData';
import { useTraffic } from '../context/TrafficContext';
import { EMERGENCY_TYPES, ROAD_NAMES } from '../data/trafficConfig';
import { calculatePhasePriority, SIGNAL_PHASES } from '../algorithms/adaptiveSignalController';
import { SENSOR_STATUS } from '../algorithms/sensorHealth';
import { getCooldownRemaining } from '../algorithms/pedestrianPriority';

function phaseLabel(phase) { return phase === 'ns' ? 'NORTH-SOUTH' : 'EAST-WEST'; }
function phaseApproaches(phase) { return phase === 'ns' ? 'North & South approaches' : 'East & West approaches'; }
function signalTone(signalState) { return signalState.state === 'GREEN' ? 'green' : signalState.state === 'YELLOW' ? 'amber' : 'coral'; }

export default function Dashboard() {
  const { trafficState, signalState, starvationState, pedestrianState, emergencyState, sensorState, sensorEvents, requestPedestrianCrossing, updatePedestrianCount, reportEmergency, config, simulationTime, totalVehicles, averageWaitingTime, generatorState } = useTraffic();
  const [emergencyRoad, setEmergencyRoad] = useState('north');
  const [emergencyType, setEmergencyType] = useState('Ambulance');
  const trafficCards = Object.entries(ROAD_NAMES).map(([road, direction]) => ({ direction, short: direction[0], vehicles: trafficState[road].totalVehicles, density: trafficState[road].density.toFixed(1), queue: trafficState[road].queueLength, waiting: trafficState[road].waitingTime, status: trafficState[road].status, tone: trafficState[road].status === 'RUSH' || trafficState[road].status === 'HIGH' ? 'coral' : trafficState[road].status === 'NORMAL' ? 'amber' : 'green' }));
  const averageQueue = Math.round(Object.values(trafficState).reduce((total, road) => total + road.queueLength, 0) / 4);
  const currentPhase = phaseLabel(signalState.phase);
  const nsPriority = calculatePhasePriority(trafficState, SIGNAL_PHASES.NS, config.priorityWeights, starvationState, config.starvation);
  const ewPriority = calculatePhasePriority(trafficState, SIGNAL_PHASES.EW, config.priorityWeights, starvationState, config.starvation);
  return <div className="page dashboard-page"><PageIntro eyebrow="Operations overview" title="Smart Adaptive Traffic Management" description="A calm, live view of intersection health, signal phases, and traffic demand." action={<div className="intro-status"><div><span>Simulation time</span><strong>00:00:{String(simulationTime).padStart(2, '0')}</strong></div><StatusBadge tone="accent">ADAPTIVE</StatusBadge></div>} />
    <div className="dashboard-banner"><div className="banner-icon"><Activity size={20} /></div><div><strong>Adaptive controller ready</strong><span>Traffic priority is calculated from density, queue length, and waiting time.</span></div><div className="banner-state"><span className="pulse-dot" />ONLINE</div></div>
    <div className="dashboard-grid top-grid"><section className="panel intersection-panel"><SectionHeading title="Live intersection" detail="Junction A-01 · 4-way control zone" action={<span className="panel-live"><span className="pulse-dot" />Live view</span>} /><TrafficIntersection emergency={emergencyState} /></section><section className="panel signal-panel"><SectionHeading title="Current signal status" detail={`Adaptive phase · ${signalState.state}`} /><div className="phase-display"><div><span className="phase-label">Current phase</span><strong>{currentPhase}</strong></div><div className="phase-timer"><span>Remaining</span><strong>{signalState.remaining}<small>sec</small></strong></div></div><div className="signal-state-row"><div className={`mini-signal ${signalTone(signalState)}`}><i /><i /><i className="lit" /></div><div><strong>{signalState.state}</strong><span>{phaseApproaches(signalState.phase)}</span></div><StatusBadge tone={signalTone(signalState)}>{signalState.state}</StatusBadge></div><div className="signal-details"><div><span>Requested green</span><strong>{signalState.requestedGreen} sec</strong></div><div><span>Approved green</span><strong>{signalState.approvedGreen} sec</strong></div><div><span>Yellow</span><strong>{config.signalTiming.yellow} sec</strong></div><div><span>All red</span><strong>{config.signalTiming.allRed} sec</strong></div></div></section></div>
    <section><SectionHeading title="Approach conditions" detail="Current traffic by direction" /><div className="traffic-card-grid">{trafficCards.map(data => <TrafficCard key={data.direction} data={data} />)}</div></section>
    <section className="panel starvation-panel"><SectionHeading title="Anti-starvation monitor" detail="Waiting priority is fed into the adaptive controller" /><div className="starvation-grid">{Object.entries(ROAD_NAMES).map(([road, direction]) => { const starvation = starvationState[road]; return <div className="starvation-row" key={road}><strong>{direction}</strong><span>Waiting: {starvation.waitingTime} sec</span><span>Red cycles: {starvation.consecutiveRedCycles}</span><b className={starvation.starvationStatus === 'STARVATION PRIORITY' ? 'starvation-priority' : starvation.starvationStatus === 'WARNING' ? 'starvation-warning' : ''}>{starvation.starvationStatus}</b><span>Score: {starvation.starvationScore.toFixed(1)}</span><span className={starvation.priorityBoost > 0 ? 'boost-active' : ''}>Priority Boost: {starvation.priorityBoost > 0 ? 'ACTIVE' : 'OFF'}</span></div>; })}</div></section>
    <section className="panel pedestrian-live-panel"><SectionHeading title="Pedestrian status" detail="Requests complete a safe vehicle transition before WALK" /><div className="pedestrian-live-grid"><label><span>Pedestrians waiting</span><input type="number" min="0" value={pedestrianState.pedestrianCount} onChange={event => updatePedestrianCount(event.target.value)} /></label><div><span>Demand</span><strong>{pedestrianState.demand}</strong></div><div><span>Request</span><strong>{pedestrianState.pedestrianRequest ? 'ACTIVE' : 'NONE'}</strong></div><div><span>Status</span><strong>{pedestrianState.status}</strong></div><div><span>Phase</span><strong>{pedestrianState.phase}</strong></div><div><span>Countdown</span><strong>{pedestrianState.countdown ? `${pedestrianState.countdown} sec` : '--'}</strong></div>{pedestrianState.status === 'COOLDOWN' && <div><span>Cooldown</span><strong>{getCooldownRemaining(pedestrianState)} sec</strong></div>}</div>{pedestrianState.lastRejectionReason && <div className="video-status warning" style={{margin:'0.75rem 0 0',padding:'0.5rem 0.75rem',fontSize:'0.82rem'}}><AlertTriangle size={14} /><span>{pedestrianState.lastRejectionReason}</span></div>}<button className="primary-button pedestrian-request-button" onClick={() => requestPedestrianCrossing(pedestrianState.pedestrianCount)} disabled={pedestrianState.status === 'COOLDOWN' || pedestrianState.status === 'PENDING' || pedestrianState.status === 'WALK'}>{pedestrianState.status === 'COOLDOWN' ? `COOLDOWN (${getCooldownRemaining(pedestrianState)}s)` : pedestrianState.status === 'PENDING' ? 'REQUEST PENDING' : 'REQUEST PEDESTRIAN CROSSING'}</button></section>
    <section className="panel emergency-live-panel"><SectionHeading title="Emergency status" detail="Critical priority still follows the safety transition layer" /><div className="emergency-form"><label><span>Road</span><select value={emergencyRoad} onChange={event => setEmergencyRoad(event.target.value)}>{Object.entries(ROAD_NAMES).map(([road, name]) => <option value={road} key={road}>{name}</option>)}</select></label><label><span>Vehicle type</span><select value={emergencyType} onChange={event => setEmergencyType(event.target.value)}>{EMERGENCY_TYPES.map(type => <option key={type}>{type}</option>)}</select></label><button className="primary-button" onClick={() => reportEmergency(emergencyRoad, emergencyType)}>REPORT EMERGENCY</button></div><div className="emergency-live-grid"><div><span>Status</span><strong>{emergencyState.status}</strong></div><div><span>Vehicle</span><strong>{emergencyState.active?.type || emergencyState.queue[0]?.type || 'NONE'}</strong></div><div><span>Road</span><strong>{emergencyState.active ? ROAD_NAMES[emergencyState.active.road] : emergencyState.queue[0] ? ROAD_NAMES[emergencyState.queue[0].road] : 'NONE'}</strong></div><div><span>Priority</span><strong>{emergencyState.queue.length ? 'CRITICAL' : 'NONE'}</strong></div><div><span>Emergency queue</span><strong>{emergencyState.queue.length ? emergencyState.queue.map(item => ROAD_NAMES[item.road]).join(' → ') : 'NONE'}</strong></div><div><span>Response time</span><strong>{emergencyState.responseTime ? `${(emergencyState.responseTime / 1000).toFixed(1)} sec` : '--'}</strong></div></div></section>
    <div className="dashboard-grid middle-grid"><section className="panel decision-panel"><SectionHeading title="Adaptive decision" action={<StatusBadge tone="green">Approved</StatusBadge>} /><div className="decision-focus"><div className="decision-arrow"><span>Current priority</span><strong>{signalState.currentPriority.toFixed(1)}</strong></div><div className="decision-reason"><span>Traffic reason</span><strong>{signalState.reason}</strong></div></div><div className="decision-values"><div><span>NS priority</span><strong>{nsPriority.toFixed(1)}</strong></div><div><span>EW priority</span><strong>{ewPriority.toFixed(1)}</strong></div><div><span>Requested green</span><strong>{signalState.requestedGreen} sec</strong></div><div><span>Approved green</span><strong>{signalState.approvedGreen} sec</strong></div></div><div className="decision-foot"><ShieldCheck size={16} /> Safety transition timing is reserved for the signal engine.</div></section><SafetyPanel /><section className="panel compact-status"><SectionHeading title="Emergency status" /><div className="status-empty"><div className="status-icon safe"><Siren size={20} /></div><div><strong>No emergency</strong><span>Emergency vehicles <b>0</b></span><span>Emergency queue <b>0</b></span></div></div><button className="secondary-button">Report emergency <span>+</span></button></section><section className="panel compact-status"><SectionHeading title="Pedestrian status" /><div className="status-empty"><div className="status-icon amber"><UsersRound size={20} /></div><div><strong>Crossing clear</strong><span>Waiting <b>0</b></span><span>Request <b>NONE</b></span></div></div><button className="secondary-button">Request crossing <span>+</span></button></section></div>
    <section><SectionHeading title="Performance summary" detail="Live traffic telemetry" action={<span className="section-link">View full comparison <span>→</span></span>} /><div className="metrics-grid"><MetricCard label="Vehicles observed" value={totalVehicles} unit=" veh" trend="Shared traffic state" icon={CarFront} /><MetricCard label="Average waiting time" value={averageWaitingTime} unit=" sec" trend="Across four approaches" icon={Clock3} tone="amber" /><MetricCard label="Average queue length" value={averageQueue} unit=" veh" trend="Estimated from demand" icon={Gauge} tone="coral" /><MetricCard label="Simulation seconds" value={simulationTime} unit=" sec" trend="Session clock" icon={Activity} /></div></section>
    <div className="dashboard-grid bottom-grid"><section className="panel chart-panel"><SectionHeading title="Traffic density" detail="Last 30 minutes · sample data" /><TrendChart type="density" data={densityData} /></section><section className="panel chart-panel"><SectionHeading title="Queue length" detail="Last 30 minutes · sample data" /><TrendChart type="queue" data={queueData} /></section><section className="panel chart-panel"><SectionHeading title="Waiting time" detail="Last 30 minutes · sample data" /><TrendChart type="waiting" data={waitingData} /></section></div>
    <section className="panel event-panel"><SectionHeading title="Live event log" detail="Most recent system activity" action={<span className="section-link">View all <span>→</span></span>} /><EventLog events={eventLog} /></section>
    <section className="panel sensor-health-panel"><SectionHeading title="Sensor health" detail="Data freshness monitoring for all approaches" /><div className="sensor-health-grid">{Object.entries(ROAD_NAMES).map(([road, name]) => { const sensor = sensorState[road]; const statusIcon = sensor.status === SENSOR_STATUS.HEALTHY ? '🟢' : sensor.status === SENSOR_STATUS.WARNING ? '🟡' : sensor.status === SENSOR_STATUS.OFFLINE ? '🔴' : '🔵'; const timeSince = Math.round((Date.now() - sensor.lastValidDataTime) / 1000); return <div className="sensor-row" key={road}><strong>{statusIcon} {name}</strong><span>Status: <b>{sensor.status}</b></span><span>Last data: {timeSince}s ago</span><span>Mode: <b>{sensor.signalMode}</b></span>{sensor.fallbackReason && <span className="sensor-fallback-reason">{sensor.fallbackReason}</span>}</div>; })}</div>{sensorEvents.length > 0 && <div className="sensor-event-log"><strong>Sensor events</strong>{sensorEvents.slice(0, 10).map((evt, i) => <div key={i} className={`sensor-event ${evt.type.toLowerCase()}`}><span>{new Date(evt.time).toLocaleTimeString()}</span><span>{evt.message}</span></div>)}</div>}</section>
    {generatorState && <section className="panel scenario-info-panel"><SectionHeading title="Scenario generator" detail={`${generatorState.label} · Seed: ${generatorState.seed}`} /><div className="scenario-info-grid"><div><span>Scenario</span><strong>{generatorState.label}</strong></div><div><span>Tick</span><strong>{generatorState.tickCount}</strong></div><div><span>Total arrivals</span><strong>{generatorState.totalArrivals}</strong></div>{generatorState.surgeActive && <div><span>Surge</span><strong className="starvation-priority">ACTIVE</strong></div>}{generatorState.surgeDescription && <div style={{gridColumn:'1/-1'}}><span>Note</span><strong>{generatorState.surgeDescription}</strong></div>}</div></section>}
  </div>;
}
