import { BarChart3, CheckCircle2, Clock3, Gauge, Trophy } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { PageIntro, SectionHeading, StatusBadge } from '../components/Shared';
import { useTraffic } from '../context/TrafficContext';

export default function PerformanceComparison() {
  const { trafficState, totalVehicles, averageWaitingTime } = useTraffic();
  const averageQueue = Math.round(Object.values(trafficState).reduce((total, road) => total + road.queueLength, 0) / 4);
  const data = [{ metric: 'Vehicles', fixed: totalVehicles, adaptive: totalVehicles }, { metric: 'Waiting', fixed: averageWaitingTime, adaptive: averageWaitingTime }, { metric: 'Queue', fixed: averageQueue, adaptive: averageQueue }, { metric: 'Roads active', fixed: Object.values(trafficState).filter(road => road.totalVehicles > 0).length, adaptive: Object.values(trafficState).filter(road => road.totalVehicles > 0).length }];
  return <div className="page"><PageIntro eyebrow="Evaluation layer" title="Performance comparison" description="Review shared traffic observations. Fixed-time and adaptive signal comparison will be added in a later step." action={<StatusBadge tone="accent">Traffic data live</StatusBadge>} /><div className="comparison-grid"><section className="comparison-card fixed"><div className="comparison-card-head"><div><span className="eyebrow">Traffic input</span><h2>Current observation</h2></div><div className="comparison-icon"><Clock3 size={19} /></div></div><p>Centralized values from simulation or manual input.</p><div className="comparison-stat"><span>Vehicles observed</span><strong>{totalVehicles} <small>veh</small></strong></div><div className="comparison-stat"><span>Average waiting time</span><strong>{averageWaitingTime} <small>sec</small></strong></div><div className="comparison-stat"><span>Average queue</span><strong>{averageQueue} <small>veh</small></strong></div></section><section className="comparison-card adaptive"><div className="comparison-card-head"><div><span className="eyebrow">Shared state</span><h2>Four approaches</h2></div><div className="comparison-icon"><Trophy size={19} /></div></div><p>Ready for future control and analytics modules.</p><div className="comparison-stat"><span>North / South / East / West</span><strong>4 <small>roads</small></strong></div><div className="comparison-stat"><span>Traffic data source</span><strong>LIVE</strong></div><div className="comparison-stat"><span>Signal comparison</span><strong>Later</strong></div></section></div><section className="panel comparison-chart"><SectionHeading title="Traffic data snapshot" detail="Current shared state · no signal optimization applied yet" /><div className="legend-row"><span><i className="legend-box fixed-box" />Observed values</span><span><i className="legend-box adaptive-box" />Shared state</span></div><div className="large-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#e8ebe6" /><XAxis dataKey="metric" tick={{ fill: '#88918d', fontSize: 10 }} /><YAxis tick={{ fill: '#88918d', fontSize: 10 }} /><Tooltip /><Bar dataKey="fixed" fill="#b8c4bd" radius={[4, 4, 0, 0]} /><Bar dataKey="adaptive" fill="#2f8077" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></section><div className="comparison-note"><CheckCircle2 size={16} /> Traffic state is centralized and ready for the future performance engine.</div></div>;
}
