import { useState } from 'react';
import { Save, SlidersHorizontal } from 'lucide-react';
import { PageIntro, SectionHeading, StatusBadge } from '../components/Shared';
import { ADAPTIVE_PRIORITY_WEIGHTS, EMERGENCY_DEFAULTS, PEDESTRIAN_DEFAULTS, STARVATION_DEFAULTS, TRAFFIC_THRESHOLDS, VEHICLE_WEIGHTS } from '../data/trafficConfig';
import { loadSettings } from '../utils/formatters';

const defaults = { minGreen: 10, maxGreen: 50, yellow: 3, allRed: 2, starvation: 45, pedestrian: 20, ...VEHICLE_WEIGHTS, ...TRAFFIC_THRESHOLDS, densityWeight: ADAPTIVE_PRIORITY_WEIGHTS.density, queueWeight: ADAPTIVE_PRIORITY_WEIGHTS.queue, waitingWeight: ADAPTIVE_PRIORITY_WEIGHTS.waiting, starvationThreshold: STARVATION_DEFAULTS.threshold, starvationWarningRatio: STARVATION_DEFAULTS.warningRatio, starvationWaitingWeight: STARVATION_DEFAULTS.waitingWeight, starvationCycleWeight: STARVATION_DEFAULTS.cycleWeight, starvationBoostWeight: STARVATION_DEFAULTS.boostWeight, pedestrianWalkDuration: PEDESTRIAN_DEFAULTS.walkDuration, pedestrianHighDemandCount: PEDESTRIAN_DEFAULTS.highDemandCount, pedestrianMaxPendingRequests: PEDESTRIAN_DEFAULTS.maxPendingRequests, emergencyGreenDuration: EMERGENCY_DEFAULTS.greenDuration, emergencyMaxQueue: EMERGENCY_DEFAULTS.maxQueue };
const timingFields = [['minGreen', 'Minimum green', 'sec'], ['maxGreen', 'Maximum green', 'sec'], ['yellow', 'Yellow', 'sec'], ['allRed', 'All red', 'sec'], ['starvation', 'Anti-starvation threshold', 'sec'], ['pedestrian', 'Pedestrian threshold', 'people']];
const thresholdFields = [['normalDensity', 'Normal density', 'density'], ['highDensity', 'High density', 'density'], ['rushDensity', 'Rush density', 'density'], ['normalVehicles', 'Normal vehicle count', 'vehicles'], ['highVehicles', 'High vehicle count', 'vehicles'], ['rushVehicles', 'Rush vehicle count', 'vehicles']];
const weightFields = [['cycle', 'Cycle'], ['bike', 'Bike'], ['auto', 'Auto'], ['car', 'Car'], ['heavy', 'Heavy vehicle']];
const priorityFields = [['densityWeight', 'Density priority'], ['queueWeight', 'Queue priority'], ['waitingWeight', 'Waiting priority']];
const starvationFields = [['starvationThreshold', 'Maximum waiting', 'sec'], ['starvationWarningRatio', 'Warning ratio', 'ratio'], ['starvationWaitingWeight', 'Waiting score weight', 'weight'], ['starvationCycleWeight', 'Red-cycle score weight', 'weight'], ['starvationBoostWeight', 'Priority boost weight', 'weight']];
const pedestrianFields = [['pedestrianWalkDuration', 'WALK duration', 'sec'], ['pedestrianHighDemandCount', 'High demand count', 'people'], ['pedestrianMaxPendingRequests', 'Max pending requests', 'requests']];
const emergencyFields = [['emergencyGreenDuration', 'Emergency green', 'sec'], ['emergencyMaxQueue', 'Maximum queue', 'requests']];

export default function Settings() {
  const [settings, setSettings] = useState(() => loadSettings(defaults));
  const [saved, setSaved] = useState(false);
  const update = (key, value) => { setSettings(current => ({ ...current, [key]: value })); setSaved(false); };
  const save = () => { localStorage.setItem('traffic-settings', JSON.stringify(settings)); window.dispatchEvent(new Event('traffic-settings-updated')); setSaved(true); };
  const renderFields = fields => <div className="settings-form">{fields.map(([key, label, unit]) => <label key={key}><span>{label}</span><div className="input-wrap"><input type="number" value={settings[key]} onChange={event => update(key, Math.max(0, Number(event.target.value) || 0))} min="0" step={key.includes('Density') ? '0.1' : '1'} /><em>{unit}</em></div></label>)}</div>;
  return <div className="page"><PageIntro eyebrow="System configuration" title="Settings" description="Tune shared traffic thresholds and adaptive signal weights." action={<StatusBadge tone={saved ? 'green' : 'muted'}>{saved ? 'Saved' : 'Local configuration'}</StatusBadge>} /><div className="settings-layout"><section className="panel settings-panel"><SectionHeading title="Signal timing" detail="Used by the adaptive phase engine" />{renderFields(timingFields)}</section><section className="panel settings-panel"><SectionHeading title="Vehicle weights" detail="Used by live traffic density calculations" />{renderFields(weightFields.map(([key, label]) => [key, label, 'weight']))}<div className="settings-callout"><SlidersHorizontal size={16} /> These values are shared with simulation, manual input, and Dashboard.</div></section><section className="panel settings-panel"><SectionHeading title="Traffic classification" detail="Used by the centralized traffic state" />{renderFields(thresholdFields)}</section><section className="panel settings-panel"><SectionHeading title="Adaptive priority weights" detail="Density + queue + waiting time" />{renderFields(priorityFields.map(([key, label]) => [key, label, 'weight']))}</section><section className="panel settings-panel"><SectionHeading title="Anti-starvation" detail="Boost waiting approaches before starvation" />{renderFields(starvationFields)}</section><section className="panel settings-panel"><SectionHeading title="Pedestrian priority" detail="Safe WALK phase configuration" />{renderFields(pedestrianFields)}</section><section className="panel settings-panel"><SectionHeading title="Emergency management" detail="Critical preemption configuration" />{renderFields(emergencyFields)}</section></div><div className="settings-actions"><span>{saved ? 'Traffic configuration updated.' : 'Changes apply after saving.'}</span><button className="primary-button" onClick={save}><Save size={15} /> Save settings</button></div></div>;
}
